version: '3.8'

services:
  servidor-web:
    image: nginx:latest
    container_name: nginx-curso-windows
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: always