version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-docker
    restart: unless-stopped
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
      - ./config/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - mariadb-network

networks:
  mariadb-network:
    driver: bridge
